services:
  wud:
    image: getwud/wud
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3004:3000"

  client:
    image: smaugtur/pokesocket-client:latest
    container_name: pokesocket-client
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=true"
      - "wud.display.name=PokeSocket Client"

  server:
    image: smaugtur/pokesocket-server:latest
    container_name: pokesocket-server
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=true"
      - "wud.display.name=PokeSocket Server"

  db:
    image: smaugtur/pokesocket-db:latest
    container_name: pokesocket-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=false"

networks:
  vpc:
    external: true

volumes:
  postgres_data: