services:
  wud:
    image: getwud/wud
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3004:3000"

  client:
    image: smaugtur/pokesocket-client:latest
    container_name: pokesocket-client
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=true"
      - "wud.display.name=PokeSocket Client"

  server:
    image: smaugtur/pokesocket-server:latest
    container_name: pokesocket-server
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=true"
      - "wud.display.name=PokeSocket Server"
    environment:
      # API
      API_PORT: "8080"
      # DB
      DB_URI: "postgresql://postgres:postgres@pokesocket-db:5432/postgres"
      # LOGGING Configuration
      LOGGING_LEVEL: "debug"
      LOGGING_PRETTY: "yes"
      # CORS Configuration
      ALLOWED_ORIGINS: "http://localhost:3001,http://localhost:3000,http://example.com"
      ALLOWED_CONTENT_TYPES: "application/json,text/plain"
      ALLOWED_METHODS: "GET,POST,PUT,DELETE,PATCH"
      ALLOWED_HEADERS: "Content-Type,Authorization"

  db:
    image: smaugtur/pokesocket-db:latest
    container_name: pokesocket-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vpc
    labels:
      - "wud.watch=false"

networks:
  vpc:
    external: true

volumes:
  postgres_data: