services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:3000
    environment:
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_LOCAL_CRON=0 0 3 * * *  # Daily at 3 AM
      - WUD_TRIGGER_DOCKER_LOCAL_SOCKET=/var/run/docker.sock
      - WUD_TRIGGER_DOCKER_UPDATE_AUTO=false