// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package users_db

import (
	"context"
)

const hello = `-- name: hello :many
SELECT id, name, email, created_at FROM users
`

func (q *Queries) hello(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, hello)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
